#ifndef _FS_API_STATUS_ID_H
#define _FS_API_STATUS_ID_H

// login status
#define FS_API_STATUS_LOGIN_SUCCESS		0x00
#define FS_API_STATUS_LOGIN_USR_PWD_ERROR	0x01
#define FS_API_STATUS_LOGIN_ACCESS_DENY		0x02
#define FS_API_STATUS_LOGIN_EXCEED_MAX_USER	0x03
#define FS_API_STATUS_LOGIN_CONNECT_FAIL	0x04
#define FS_API_STATUS_LOGIN_ERROR_UNKNOW	0x05



// open video status
#define FS_API_STATUS_OPEN_VIDEO_SUCCESS	0x10
#define FS_API_STATUS_OPEN_VIDEO_CONNECTING	0x11
#define FS_API_STATUS_OPEN_VIDEO_FAIL		0x12

// open audio status
#define FS_API_STATUS_OPEN_AUDIO_SUCCESS	0x20
#define FS_API_STATUS_OPEN_AUDIO_FAIL		0x21
#define FS_API_STATUS_CLOSE_AUDIO_SUCCESS	0x22
#define FS_API_STATUS_CLOSE_AUDIO_FAIL		0x23

// talk
#define FS_API_STATUS_OPEN_TALK_SUCCESS		0x30
#define FS_API_STATUS_OPEN_TALK_FAIL_ACCESS_DENY 0x31
#define FS_API_STATUS_OPEN_TALK_FAIL_USED_BY_ANOTHER_USER 0x32
#define FS_API_STATUS_CLOSE_TALK_SUCCESS	0x33
#define FS_API_STATUS_CLOSE_TALK_FAIL		0x34


// record
#define FS_API_STATUS_RECORD_REQUEST_CHANNEL_1             0x40
#define FS_API_STATUS_RECORD_REQUEST_CHANNEL_2             0x41
#define FS_API_STATUS_RECORD_REQUEST_CHANNEL_3             0x42
#define FS_API_STATUS_RECORD_REQUEST_CHANNEL_4             0x43

#endif
